# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b08aed7385a714103702fb6b29920d0c8952f8c12cc941715951ed666521f02e1714680a91893a2a32b7f2c455228359eb81e3a20defcf488ae5c15b151d1dc

test:
  secret_key_base: 7384ecb65aec6b89ae5b1a3a574fc256e610f12c3226e0e4b1b7e8f470a6d2af3d285d29a8a35b90978931f83bf536af7a72aada3384eab23b2c0b28e71cb6b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
